name: Acquire Activation File
on:
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/activation.yml
jobs:
  activation:
    name: Request Manual Activation File
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      # Request manual activation file using game-ci
      - uses: game-ci/unity-request-activation-file@v2
        id: getManualLicenseFile
        with:
          unityVersion: 6000.3.5f1

      # Upload the generated .alf file as an artifact
      - uses: actions/upload-artifact@v4
        with:
          name: Unity_v6000.3.5f1.alf
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
